sudo: required

language: node_js

services:
  - docker
  - docker-compose

script:
  - docker-compose up user_test
  - docker-compose up user_build

  - docker-compose up editor_test
  - docker-compose up editor_build

  - docker-compose up admin_test
  - docker-compose up admin_build

  - docker-compose up server_test
