version: "3.2"
services:
  # Editor client
  editor_dev:
    image: node:11.0-alpine
    container_name: editor_client_dev
    working_dir: /app
    command: yarn start
    ports:
      - "8082:8080"
    volumes:
      - type: bind
        source: ./clients/editor
        target: /app
  editor_build:
    image: node:11.0-alpine
    container_name: editor_client_build
    working_dir: /app
    command: yarn build
    volumes:
      - type: bind
        source: ./clients/editor
        target: /app
  editor_test:
    image: node:11.0-alpine
    container_name: editor_client_test
    working_dir: /app
    command: yarn test
    volumes:
      - type: bind
        source: ./clients/editor
        target: /app
  # Admin client
  admin_dev:
    image: node:10-alpine # TODO: Change to node:11-alpine lately
    container_name: admin_client_dev
    network_mode: "host" # parcer-bundler has some side-effect with ports, so it's better solution TODO: change to port 8083
    working_dir: /app
    command: yarn start
    volumes:
      - type: bind
        source: ./clients/admin
        target: /app
  admin_build:
    image: node:10-alpine
    container_name: admin_client_build
    working_dir: /app
    command: yarn build
    volumes:
      - type: bind
        source: ./clients/admin
        target: /app
  admin_test:
    image: node:10-alpine
    container_name: admin_client_test
    working_dir: /app
    command: yarn test
    volumes:
      - type: bind
        source: ./clients/admin
        target: /app
  # User client
  # user_dev: # TODO: fix it
  #   image: node:11.0-alpine
  #   container_name: user_client_dev
  #   working_dir: /app
  #   ports:
  #     - "8081:8081"
    command: yarn serve
    volumes:
      - type: bind
        source: ./clients/user
        target: /app
  user_build:
    image: node:11.0-alpine
    container_name: user_client_build
    working_dir: /app
    command: yarn build
    volumes:
      - type: bind
        source: ./clients/user
        target: /app
  user_test:
    image: node:11.0-alpine
    container_name: user_client_test
    working_dir: /app
    command: yarn lint
    volumes:
      - type: bind
        source: ./clients/user
        target: /app
  # Database
  database_dev:
    image: mongo:4.0
    container_name: database_dev
    network_mode: "service:server_dev"
  # Server
  server_dev:
    image: node:11.0-alpine
    container_name: server_dev
    working_dir: /app
    command: yarn dev-start
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./server
        target: /app
  server_test:
    image: node:11.0-alpine
    container_name: server_dev
    working_dir: /app
    command: yarn test
    volumes:
      - type: bind
        source: ./server
        target: /app
