# Editor client
version: "3.2"
services:
  editor_dev:
    image: node:11.0-alpine
    container_name: editor_dev
    working_dir: /app
    command: yarn start
    ports:
      - "8082:8082"
    volumes:
      - type: bind
        source: .
        target: /app
  editor_build:
    image: node:11.0-alpine
    container_name: editor_build
    working_dir: /app
    command: yarn build
    volumes:
      - type: bind
        source: .
        target: /app
  editor_test:
    image: node:11.0-alpine
    container_name: editor_test
    working_dir: /app
    command: yarn test
    volumes:
      - type: bind
        source: .
        target: /app
  server:
    image: node:11.0-alpine
    container_name: server-editor
    working_dir: /app
    command: yarn dev-start
    network_mode: "service:editor_dev"
    volumes:
      - type: bind
        source: ../../server
        target: /app
  database:
    image: mongo:4.0
    container_name: database-editor
    network_mode: "service:server"
