version: "3.2"
services:
  server_dev:
    image: node:11.0-alpine
    container_name: server_dev
    working_dir: /app
    command: yarn dev-start
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /app
  server_test:
    image: node:11.0-alpine
    container_name: server_test
    working_dir: /app
    command: yarn test
    volumes:
      - type: bind
        source: .
        target: /app
  database:
    image: mongo:4.0
    container_name: database-server
    network_mode: "service:server_dev"
