# Admin client
version: "3.2"
services:
  admin_dev:
    image: node:10-alpine # TODO: Change to node:11-alpine lately
    container_name: admin_client_dev
    network_mode: "host" # parcer-bundler has some side-effect with ports, so it's better solution TODO: change to port 8083
    working_dir: /app
    command: yarn start
    volumes:
      - type: bind
        source: .
        target: /app
  admin_build:
    image: node:10-alpine
    container_name: admin_build
    working_dir: /app
    command: yarn build
    volumes:
      - type: bind
        source: .
        target: /app
  admin_test:
    image: node:10-alpine
    container_name: admin_test
    working_dir: /app
    command: yarn test
    volumes:
      - type: bind
        source: .
        target: /app
  server:
    image: node:11.0-alpine
    container_name: server-admin
    working_dir: /app
    command: yarn dev-start
    network_mode: "service:admin_dev"
    volumes:
      - type: bind
        source: ../../server
        target: /app
  database:
    image: mongo:4.0
    container_name: database-admin
    network_mode: "service:server"
